export const menuItems = [
  {
    name: 'FRIED CHICKEN CHOP',
    price: 'RM 14.90',
    category: 'filter-starters',
    image: '/img/menu/img1.jpeg',
    ingredients: '',
  },
  {
    name: 'CHICKEN GRILL',
    price: 'RM 14.90',
    category: 'filter-specialty',
    image: '/img/menu/img2.png',
    ingredients: '',
  },
  {
    name: 'FRIED CHICKEN CHOP ',
    price: 'RM 16.90',
    category: 'filter-starters',
    image: '/img/menu/img3.png',
    ingredients: 'with cheese',
  },
  {
    name: 'FRIED CHICKEN CHOP',
    price: 'RM 16.90',
    category: 'filter-starters',
    image: '/img/menu/img4.png',
    ingredients: 'with fried rice',
  },
  {
    name: 'CHICKEM CHOP',
    price: 'RM 18.90',
    category: 'filter-salads',
    image: '/img/menu/img5.png',
    ingredients: 'with spaghetti carbonara',
  },
  {
    name: 'CHICKEM CHOP',
    price: 'RM 18.90',
    category: 'filter-salads',
    image: '/img/menu/img6.png',
    ingredients: 'with spaghetti bolognese',
  },
  {
    name: 'CHICKEM CHOP',
    price: 'RM 18.90',
    category: 'filter-salads',
    image: '/img/menu/img7.png',
    ingredients: 'with spaghetti cremy cheese',
  },
  {
    name: 'CHICKEM CHOP',
    price: 'RM 18.90',
    category: 'filter-salads',
    image: '/img/menu/img8.png',
    ingredients: 'with spaghetti creamy butter',
  },
  {
    name: 'CHICKEM CHOP',
    price: 'RM 18.90',
    category: 'filter-salads',
    image: '/img/menu/img9.png',
    ingredients: 'with macoroni carbonara',
  },
  {
    name: 'CHICKEM CHOP',
    price: 'RM 18.90',
    category: 'filter-salads',
    image: '/img/menu/img10.png',
    ingredients: 'with macoroni bolognese',
  },
  {
    name: 'LAMB CHOP',
    price: 'RM 18.90',
    category: 'filter-specialty',
    image: '/img/menu/img11.png',
    ingredients: '',
  },
  {
    name: 'LAMB CHOP',
    price: 'RM 17.90',
    category: 'filter-specialty',
    image: '/img/menu/img12.png',
    ingredients: 'with spaghetti bolognese',
  },
  {
    name: 'LAMB CHOP ',
    price: 'RM 18.90',
    category: 'filter-specialty',
    image: '/img/menu/img13.png',
    ingredients: 'with spaghetti carbonara',
  },
  {
    name: 'LAMB CHOP ',
    price: 'RM 18.90',
    category: 'filter-specialty',
    image: '/img/menu/img14.png',
    ingredients: 'with macoroni carbonara',
  },
  {
    name: 'LAMB CHOP',
    price: 'RM 18.90',
    category: 'filter-specialty',
    image: '/img/menu/img15.png',
    ingredients: 'with macoroni bolognese',
  },

  {
    name: 'BEEF STICK',
    price: 'RM 20.60',
    category: 'filter-salads',
    image: '/img/menu/img16.png',
    ingredients: '',
  },
  {
    name: 'FRIED CHICKEN CHOP BREAST ',
    price: 'RM 16.00',
    category: 'filter-starters',
    image: '/img/menu/img17.png',
    ingredients: 'with SPAGHETTI CARBONARA',
  },
  {
    name: 'GRILL CHICKEN CHOP',
    price: 'RM 15.90',
    category: 'filter-specialty',
    image: '/img/menu/img18.png',
    ingredients: 'with fried rice',
  },
  {
    name: 'FISH AND CHIPS',
    price: 'RM 13.90',
    category: 'filter-specialty',
    image: '/img/menu/img19.png',
    ingredients: '',
  },
  {
    name: 'FRIED CHICKEN ',
    price: 'RM 16.00',
    category: 'filter-starters',
    image: '/img/menu/img20.png',
    ingredients: 'chop breast with spaghetti carbonara',
  },
  {
    name: 'SPAGHETTI ',
    price: 'RM 9.90',
    category: 'filter-salads',
    image: '/img/menu/img21.png',
    ingredients: 'chiecken bolognese',
  },
  {
    name: 'FISH AND CHIPS',
    price: 'RM 14.90',
    category: 'filter-specialty',
    image: '/img/menu/img22.png',
    ingredients: 'with fried rice',
  },
  {
    name: 'FRIED CHICKEN',
    price: 'RM 16.00',
    category: 'filter-starters',
    image: '/img/menu/img23.png',
    ingredients: 'chop breast with creamy cheese',
  },
  {
    name: 'SPAGHETTI',
    price: 'RM 12.00',
    category: 'filter-salads',
    image: '/img/menu/img24.png',
    ingredients: 'chicken bolognese cheese',
  },
  {
    name: 'FRIED CHICKEN ',
    price: 'RM 12.50',
    category: 'filter-starters',
    image: '/img/menu/img25.png',
    ingredients: 'chop breast',
  },
  {
    name: 'FRIED CHICKEN ',
    price: 'RM 15.00',
    category: 'filter-starters',
    image: '/img/menu/img26.png',
    ingredients: 'chop breast with creamy butter',
  },
  {
    name: 'SPAGHETTI',
    price: 'RM 11.90',
    category: 'filter-salads',
    image: '/img/menu/img27.png',
    ingredients: 'with chicken creamy butter',
  },
  {
    name: 'FRIED CHICKEN',
    price: 'RM 15.50',
    category: 'filter-starters',
    image: '/img/menu/img28.png',
    ingredients: 'chop breast with fried rice',
  },

  {
    name: 'SPAGHETTI ',
    price: 'RM 9.90',
    category: 'filter-salads',
    image: '/img/menu/img29.png',
    ingredients: 'chicken carbonara',
  },
  {
    name: 'SPAGHETTI ',
    price: 'RM 13.90',
    category: 'filter-salads',
    image: '/img/menu/img30.png',
    ingredients: 'with seafood carbonara',
  },
  {
    name: 'SPAGHETTI',
    price: 'RM 14.60',
    category: 'filter-salads',
    image: '/img/menu/img31.png',
    ingredients: 'with seafood bolognese',
  },
  {
    name: 'SPAGHETTI',
    price: 'RM 8.20',
    category: 'filter-salads',
    image: '/img/menu/img32.png',
    ingredients: 'with vegatables',
  },
  {
    name: 'CHICKEN PASTA',
    price: 'RM 12.50',
    category: 'filter-salads',
    image: '/img/menu/img33.png',
    ingredients: 'creamy cheese ',
  },
  {
    name: 'MACORANI',
    price: 'RM 10.40',
    category: 'filter-salads',
    image: '/img/menu/img34.png',
    ingredients: 'with chicken carbonara',
  },
  {
    name: 'CHICKEN PASTA',
    price: 'RM 10.40',
    category: 'filter-salads',
    image: '/img/menu/img35.png',
    ingredients: 'carbonara',
  },
  {
    name: 'BEEF PASTA',
    price: 'RM 12.90',
    category: 'filter-salads',
    image: '/img/menu/img36.png',
    ingredients: 'creamy cheese',
  },
  {
    name: 'MACORANI',
    price: 'RM 10.40',
    category: 'filter-salads',
    image: '/img/menu/img37.png',
    ingredients: 'with chicken bolognese',
  },
  {
    name: 'CHICKEN PASTA ',
    price: 'RM 10.40',
    category: 'filter-salads',
    image: '/img/menu/img38.png',
    ingredients: 'bolognese',
  },
  {
    name: 'SPAGHETTI',
    price: 'RM 10.40',
    category: 'filter-salads',
    image: '/img/menu/img39.png',
    ingredients: 'bolognaise chicken meatball',
  },
  {
    name: 'MACORANI',
    price: 'RM 14.60',
    category: 'filter-salads',
    image: '/img/menu/img40.png',
    ingredients: 'with seafood carbonara',
  },
  {
    name: 'BEEF PASTA',
    price: 'RM 12.10',
    category: 'filter-salads',
    image: '/img/menu/img41.png',
    ingredients: 'carbonara',
  },
  {
    name: 'SPAGHETTI',
    price: 'RM 14.60',
    category: 'filter-salads',
    image: '/img/menu/img42.png',
    ingredients: 'carbonara chicken meatball',
  },
  {
    name: 'BEEF PASTA',
    price: 'RM 12.10',
    category: 'filter-salads',
    image: '/img/menu/img43.png',
    ingredients: 'bolognese',
  },


  {
    name: 'SPAGHETTI',
    price: 'RM 14.60',
    category: 'filter-salads',
    image: '/img/menu/img44.png',
    ingredients: 'with seafood carbonara',
  },
  {
    name: 'SPAGHETTI',
    price: 'RM 10.90',
    category: 'filter-salads',
    image: '/img/menu/img45.png',
    ingredients: 'chicken spices',
  },
  {
    name: 'PASTA',
    price: 'RM 10.90',
    category: 'filter-salads',
    image: '/img/menu/img46.png',
    ingredients: 'beef spices',
  },
  {
    name: 'DRY WANTA MEE',
    price: 'RM 9.90',
    category: 'filter-starters',
    image: '/img/menu/img47.png',
    ingredients: 'with chicken sausage',
  },
  {
    name: 'SPAGHETTI',
    price: 'RM 10.90',
    category: 'filter-salads',
    image: '/img/menu/img48.png',
    ingredients: 'beef spices',
  },
  {
    name: 'WANTA MEE',
    price: 'RM 10.90',
    category: 'filter-starters',
    image: '/img/menu/img49.png',
    ingredients: 'with dumpling soup',
  },
  {
    name: 'DRY WANTA',
    price: 'RM 11.90',
    category: 'filter-starters',
    image: '/img/menu/img50.png',
    ingredients: 'mee with beef',
  },
  {
    name: 'MACORONI',
    price: 'RM 10.90',
    category: 'filter-salads',
    image: '/img/menu/img51.png',
    ingredients: 'chiecken spices',
  },
  {
    name: 'DRY WANTA MEE',
    price: 'RM 10.90',
    category: 'filter-starters',
    image: '/img/menu/img52.png',
    ingredients: 'with dumpling',
  },
  {
    name: 'CANTONI YEE MEE',
    price: 'RM 10.90',
    category: 'filter-starters',
    image: '/img/menu/img53.png',
    ingredients: 'mee with chicken',
  },
  {
    name: 'MACRONI',
    price: 'RM 10.90',
    category: 'filter-salads',
    image: '/img/menu/img54.png',
    ingredients: 'beef spices',
  },
  {
    name: 'DUMPLING SOUP',
    price: 'RM 7.40',
    category: 'filter-starters',
    image: '/img/menu/img55.png',
    ingredients: '',
  },
  {
    name: 'CANTONESE YEE MEE',
    price: 'RM 11.90',
    category: 'filter-starters',
    image: '/img/menu/img56.png',
    ingredients: 'with beef',
  },

  {
    name: 'PASTA',
    price: 'RM 10.90',
    category: 'filter-salads',
    image: '/img/menu/img57.png',
    ingredients: 'chicken spices',
  },
  {
    name: 'DAY WANTA MEE',
    price: 'RM 11.90',
    category: 'filter-starters',
    image: '/img/menu/img58.png',
    ingredients: 'with chicken breast grill',
  },
  {
    name: 'CANTONESE YEE MEE',
    price: 'RM 12.90',
    category: 'filter-starters',
    image: '/img/menu/img59.png',
    ingredients: 'with seafood',
  },
  {
    name: 'CANTONESE YEE MEE',
    price: 'RM 10.40',
    category: 'filter-starters',
    image: '/img/menu/img60.png',
    ingredients: 'with vegatables',
  },
  {
    name: 'CHICKEN KUEY TEOW ',
    price: 'RM 12.90',
    category: 'filter-starters',
    image: '/img/menu/img61.png',
    ingredients: 'soup',
  },
  {
    name: 'CHEESE BAKED ',
    price: 'RM 19.90',
    category: 'filter-specialty',
    image: '/img/menu/img62.png',
    ingredients: 'macoroni carbonara with chicken chop',
  },
  {
    name: 'DUMPILING SOUP',
    price: 'RM 10.90',
    category: 'filter-starters',
    image: '/img/menu/img63.png',
    ingredients: 'with fried rice',
  },
  {
    name: 'CHEESE BAKED',
    price: 'RM 19.90',
    category: 'filter-specialty',
    image: '/img/menu/img64.png',
    ingredients: 'chicken chop with rice',
  },
  {
    name: 'CHEESE BAKED',
    price: 'RM 19.90',
    category: 'filter-specialty',
    image: '/img/menu/img65.png',
    ingredients: 'pasta bolognese with chicken chop',
  },
  {
    name: 'CANTONESE CHICKEN',
    price: 'RM 9.90',
    category: 'filter-starters',
    image: '/img/menu/img66.png',
    ingredients: 'with fried rice',
  },
  {
    name: 'CHEESE BAKED',
    price: 'RM 19.90',
    category: 'filter-specialty',
    image: '/img/menu/img67.png',
    ingredients: 'spaghetti bolognese with chicken chop',
  },
  {
    name: 'CHEESE BAKED',
    price: 'RM 19.90',
    category: 'filter-specialty',
    image: '/img/menu/img68.png',
    ingredients: 'pasta carbonara with chicken chop',
  },
  {
    name: 'CANTONESE BEEF',
    price: 'RM 10.90',
    category: 'filter-starters',
    image: '/img/menu/img69.png',
    ingredients: 'with fried rice',
  },
  {
    name: 'CHEESE BAKED',
    price: 'RM 19.90',
    category: 'filter-specialty',
    image: '/img/menu/img70.png',
    ingredients: 'spaghetti carbonara with chicken chop',
  },

  {
    name: 'CANTONESE SEAFOOD',
    price: 'RM 13.90',
    category: 'filter-specialty',
    image: '/img/menu/img71.png',
    ingredients: 'with fried rice',
  },


  {
    name: 'CHEESE BAKED',
    price: 'RM 19.90',
    category: 'filter-specialty',
    image: '/img/menu/img72.png',
    ingredients: 'macroni bolognese with chicken chop',
  },
  {
    name: 'WEDGES',
    price: 'RM 9.90',
    category: 'filter-specialty',
    image: '/img/menu/img73.png',
    ingredients: '',
  },

  {
    name: 'FRIED DUMPLING',
    price: 'RM 7.90',
    category: 'filter-specialty',
    image: '/img/menu/img74.png',
    ingredients: '',
  },

  {
    name: 'CHICKEN MARRYLAND',
    price: 'RM 17.90',
    category: 'filter-specialty',
    image: '/img/menu/img75.png',
    ingredients: '',
  },
  {
    name: 'CHEEZY CHICKEN ROLL',
    price: 'RM 9.90',
    category: 'filter-specialty',
    image: '/img/menu/img76.png',
    ingredients: '',
  },

  {
    name: 'MUSHROOM SOUP',
    price: 'RM 9.90',
    category: 'filter-specialty',
    image: '/img/menu/img77.png',
    ingredients: 'with garlic bread',
  },

  {
    name: 'FIRED BUTTERMILK',
    price: 'RM 17.90',
    category: 'filter-specialty',
    image: '/img/menu/img78.png',
    ingredients: 'chicken rice ',
  },
  {
    name: 'GRILL GARLIC',
    price: 'RM 9.90',
    category: 'filter-specialty',
    image: '/img/menu/img79.png',
    ingredients: 'chicken',
  },

  {
    name: 'ONION RINGS',
    price: 'RM 7.90',
    category: 'filter-specialty',
    image: '/img/menu/img80.png',
    ingredients: '',
  },

  {
    name: 'SNACK PLATE',
    price: 'RM 8.90',
    category: 'filter-specialty',
    image: '/img/menu/img81.png',
    ingredients: '',
  },
  {
    name: 'YEE MEE SIZZLING',
    price: 'RM 8.90',
    category: 'filter-specialty',
    image: '/img/menu/img82.png',
    ingredients: '',
  },

  {
    name: 'NASI LEMAK SIZZLING',
    price: 'RM 10.90',
    category: 'filter-specialty',
    image: '/img/menu/img83.png',
    ingredients: 'ayam',
  },

  {
    name: 'GRILL MUSHROOM',
    price: 'RM 15.90',
    category: 'filter-specialty',
    image: '/img/menu/img84.png',
    ingredients: 'chicken',
  },
  {
    name: 'SIZZILING GRILL',
    price: 'RM 21.00',
    category: 'filter-specialty',
    image: '/img/menu/img85.png',
    ingredients: 'lamb chop',
  },

  {
    name: 'NASI LEMAK SIZZLING',
    price: 'RM 10.90',
    category: 'filter-specialty',
    image: '/img/menu/img86.png',
    ingredients: 'kambing',
  },


  {
    name: 'NASI LEMAK SIZZLING',
    price: 'RM 16.90',
    category: 'filter-specialty',
    image: '/img/menu/img87.png',
    ingredients: 'lamb chop',
  },
  {
    name: 'NASI LEMAK ',
    price: 'RM 10.90',
    category: 'filter-specialty',
    image: '/img/menu/img88.png',
    ingredients: 'chicken chop',
  },

  {
    name: 'SIZZING MIX GRILL',
    price: 'RM 25.90',
    category: 'filter-specialty',
    image: '/img/menu/img89.png',
    ingredients: '',
  },

  {
    name: 'FISH  CHIP SPAGHEETI',
    price: 'RM 15.90',
    category: 'filter-starters',
    image: '/img/menu/img90.png',
    ingredients: '',
  },
  {
    name: 'FRENCH FRIES',
    price: 'RM 10.90',
    category: 'filter-starters',
    image: '/img/menu/img91.png',
    ingredients: '',
  },

  {
    name: 'BBQ CHICKEN CHOP ',
    price: 'RM 25.90',
    category: 'filter-starters',
    image: '/img/menu/img92.png',
    ingredients: '',
  },
]